/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xinguard_parse_NatFlowNative */

#ifndef _Included_com_xinguard_parse_NatFlowNative
#define _Included_com_xinguard_parse_NatFlowNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xinguard_parse_NatFlowNative
 * Method:    setPath
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_xinguard_parse_NatFlowNative_setPath
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_xinguard_parse_NatFlowNative
 * Method:    read
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xinguard_parse_NatFlowNative_read
  (JNIEnv *, jobject);

/*
 * Class:     com_xinguard_parse_NatFlowNative
 * Method:    getDate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_xinguard_parse_NatFlowNative_getDate
  (JNIEnv *, jobject);

/*
 * Class:     com_xinguard_parse_NatFlowNative
 * Method:    getSrcAddr
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_xinguard_parse_NatFlowNative_getSrcAddr
  (JNIEnv *, jobject);

/*
 * Class:     com_xinguard_parse_NatFlowNative
 * Method:    getSrcPort
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xinguard_parse_NatFlowNative_getSrcPort
  (JNIEnv *, jobject);

/*
 * Class:     com_xinguard_parse_NatFlowNative
 * Method:    getNatAddr
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_xinguard_parse_NatFlowNative_getNatAddr
  (JNIEnv *, jobject);

/*
 * Class:     com_xinguard_parse_NatFlowNative
 * Method:    getNatPort
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xinguard_parse_NatFlowNative_getNatPort
  (JNIEnv *, jobject);

/*
 * Class:     com_xinguard_parse_NatFlowNative
 * Method:    getDestAddr
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_xinguard_parse_NatFlowNative_getDestAddr
  (JNIEnv *, jobject);

/*
 * Class:     com_xinguard_parse_NatFlowNative
 * Method:    getDestPort
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xinguard_parse_NatFlowNative_getDestPort
  (JNIEnv *, jobject);

/*
 * Class:     com_xinguard_parse_NatFlowNative
 * Method:    getProtocol
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xinguard_parse_NatFlowNative_getProtocol
  (JNIEnv *, jobject);

/*
 * Class:     com_xinguard_parse_NatFlowNative
 * Method:    getSession
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_xinguard_parse_NatFlowNative_getSession
  (JNIEnv *, jobject);

/*
 * Class:     com_xinguard_parse_NatFlowNative
 * Method:    getTransmitPacket
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_xinguard_parse_NatFlowNative_getTransmitPacket
  (JNIEnv *, jobject);

/*
 * Class:     com_xinguard_parse_NatFlowNative
 * Method:    getTransmitByte
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_xinguard_parse_NatFlowNative_getTransmitByte
  (JNIEnv *, jobject);

/*
 * Class:     com_xinguard_parse_NatFlowNative
 * Method:    getReceivePacket
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_xinguard_parse_NatFlowNative_getReceivePacket
  (JNIEnv *, jobject);

/*
 * Class:     com_xinguard_parse_NatFlowNative
 * Method:    getReceiveByte
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_xinguard_parse_NatFlowNative_getReceiveByte
  (JNIEnv *, jobject);

/*
 * Class:     com_xinguard_parse_NatFlowNative
 * Method:    getDuration
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xinguard_parse_NatFlowNative_getDuration
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
